artefactual-labs/ansible-archivematica-src

tasks/main.yml
This adds the following fixes I needed to be able to install on Trusty and with current versions of qa/1.x.
This may not be enabled by default, and is a requirement for installing the JHOVE package for MCPClient.
This is no longer used by Archivematica and, since it’s not packaged for Trusty, also prevents the packages from being installed on 14.04.
@hakamine mentioned needing to do this on 14.04, but I don't know if it breaks 12.04.
=> Trusty fixes

tasks/main.yml
Without passing this option, the script may attempt to prompt a user for action, which will hang forever since this is running in a script.
=> Specify --noinput when calling syncdb

tasks/main.yml
Using Ansible's `file` module (with `state=link`) to install the source code files in the system via symlinks which eases the workflow of the developer (relates to issue #6).
Also, this PR adds two missing dependencies (libssl-dev and libffi-dev) required to build the archivematica-storage-service virtual environment (I could make this its own PR if needed).
=> Use symlinks when installing sources, refs #6

tasks/main.yml
debian/postinst overwrites that symlink so the file module will fail next time
when it realizes the symlink disappeared. Fixes #11.
=> Don't try to symlink storage.ini (uWSGI), refs #11

README.md, defaults/main.yml, tasks/archivematica-common.yml, tasks/tear-up.yml
* Rename unused amdev_branch to amdev_version
* remove `sudo: 'no'` from saving AM commit. SS doesn't have it, and it caused problems when mounting the codebase instead of checking it out.
* Install fish in common
=> Misc fixes

tasks/archivematica-mcp-client.yml
freshclam stalls often (probably caused by clamav
server issues) when run by this role.
As a workaround, download the clamav signatures
from a github repo to avoid the need to run freshclam.
The signature files are recent but not guaranteed
to be the latest ones, however those should be
updated by freshclam later.
=> Don't run freshclam on installation

tasks/archivematica-dashboard.yml
For the appraisal tab. Requires bower to be installed, which requires npm.
The other option is to vendor the dependencies we need. This was discussed in artefactual-labs/appraisal-tab#68
=> Install bower dependencies

README.md, defaults/main.yml, tasks/pipeline-dbconf.yml
Add tasks to re-create the MCP database if desired.
To run these tasks set archivematica_src_reset_mcpdb to true (default
value: false)
=> Add tasks to re-create MCP database

tasks/pipeline-osconf.yml
Use xargs -0 and find -print0.  Now a redeploy works when names like `evelyn's photos` is in /var/archivematica/
=> Fix xargs to work with names with quotes

tasks/am-devtools.yml
am graph-links requires pygraphviz, so install those dependencies.
=> Add pygraphviz dependencies

tasks/archivematica-storage-service.yml, tasks/automation-tools.yml, tasks/pipeline-deps.yml
Pip updates Python dependencies to the latest version when re-running. This will be important for the Django 1.5 -> 1.7 upgrade, though other fixes may be required for that.
=> Pip updates to latest version

templates/etc_apache2_sites_dashboard.conf.j2
django.wsgi is part of the application, its sources are managed in the repo.
Configuration should be managed from Apache (or your fav server).
This pull request is going to be necessary once https://github.com/artefactual/archivematica/pull/358 is merged because `django.wsgi` won't provide a default `DJANGO_SETTINGS_MODULE`.
It's backward compatible, it won't break if the `django.wsgi`file does not content the changes included in #358.
=> Define environment variables and PYTHONPATH in Apache 

tasks/am-devtools.yml, tasks/appraisal-tab.yml, tasks/archivematica-storage-service.yml, tasks/pipeline-deps.yml, tasks/pipeline-osconf.yml, tasks/tear-up.yml
I started using ansible 2.0 and it displays suggestions and deprecation warnings.
It also suggests we use the synchronize module instead of rsync, but I had trouble fixing it.
```
- name: "Create /var/archivematica/sharedDirectory structure"
command: "rsync -a {{ archivematica_src_dir }}/archivematica/src/MCPServer/share/sharedDirectoryStructure/ /var/archivematica/sharedDirectory/"
```
The current playbooks all seem to work without changes in ansible 2.0.
=> Ansible 2.0 upgrades.

defaults/main.yml, tasks/archivematica-storage-service.yml, tasks/main.yml, tasks/pipeline-dbconf.yml, tasks/pipeline-instcode.yml, tasks/pipeline-osconf.yml, templates/etc_archivematica_MCPClient_clientConfig.conf.j2, templates/etc_archivematica_MCPServer_serverConfig.conf.j2, templates/etc_archivematica_archivematicaCommon_dbsettings.j2
* Template files in /etc/archivematica ( do not symlink from source code) 
* Add pythonpath to AM db django syncdb (required by source code changes)
* Tag name fixes for consistency
* Change default source install dir to /opt/archivematica
* Fix default install AM/SS branches (remove "remotes/origin/" prefix)
* Fix var name typo (django secret key)
=> Several fixes

tasks/pipeline-dbconf.yml, tasks/pipeline-instcode.yml
Preserve mysql seed & mysql_dev scripts behaviour in archivematica_src_pre_migration var.
Note: only tested for new install, now upgrades.
=> Add Django migrations support

tasks/pipeline-deps.yml
I was running into this error when standing up an archivematica vagrant:
Downloading/unpacking mysqlclient>=1.3,<2 (from agentarchives==0.1->-r /vagrant/src/archivematica/src/archivematicaCommon/requirements/base.txt (line 7))
Running setup.py (path:/tmp/pip_build_root/mysqlclient/setup.py) egg_info for package mysqlclient
sh: 1: mysql_config: not found
Traceback (most recent call last):
File "<string>", line 17, in <module>
File "/tmp/pip_build_root/mysqlclient/setup.py", line 17, in <module>
metadata, options = get_config()
File "setup_posix.py", line 44, in get_config
libs = mysql_config("libs_r")
File "setup_posix.py", line 26, in mysql_config
raise EnvironmentError("%s not found" % (mysql_config.path,))
EnvironmentError: mysql_config not found
Complete output from command python …
=> Add mysql client dev package to provide the mysql_config binary.

tasks/appraisal-tab.yml
This will need to get updated again once the appraisal tab is no longer installed via a submodule, but this fixes dependency installation for now.
=> Update appraisal tab installation method

tasks/pipeline-deps.yml
Some Archivematica branches have a MCPClient requirements.txt.  I haven't tested this with a branch that doesn't have that file.
=> Install MCPClient requirements.txt

templates/etc_archivematica_archivematicaCommon_dbsettings.j2
When using `read_default_file` (old `databaseInterface.py` uses it), the `db` parameter seems to be ignored. It's an alternative name for `database`. Oracle recommends to use `database` and it seems to work in our case. See https://dev.mysql.com/doc/connector-python/en/connector-python-connectargs.html.
Related: https://github.com/artefactual/archivematica/pull/439
=> dbsettings: use database instead of db

tasks/ss-main.yml
Use Tastypie's manage.py backfill_api_keys to ensure old users have API keys on upgrade.
I haven't had a chance to test this, feel free to amend changes into this commit, @hakamine
=> Back-create API keys for SS users

defaults/main.yml, tasks/main.yml, tasks/pipeline-websrv-gunicorn.yml, tasks/pipeline-websrv-modwsgi.yml, templates/etc_archivematica_dashboard.gunicorn-config.py.j2, templates/etc_init_archivematica-dashboard.conf.j2, templates/etc_nginx_sites_dashboard-gunicorn.conf.j2
Add variable archivematica_src_am_dashboard_gunicorn. If true,
dashboard will be configured to use gunicorn/nginx instead of
apache2/mod_wsgi. For now, default value is false.
=> Add dashboard gunicorn configuration

tasks/ss-main.yml
Storage Service is now storing config files in /etc/archivematica.
Fixes #75
=> SS: Create /etc/archivematica directory

tasks/ss-db.yml
Set the SS DB permissions after deleting & recreating it. Otherwise, gets a cannot write to read only DB error.
=> Fix SS DB permissions after resetting

README.md, tasks/pipeline-dbconf.yml
Fix tags so migrations work when only running amsrc-pipeline-dbconf-syncdb
=> Fix tags for amsrc-pipeline-dbconf-syncdb

tasks/ss-main.yml
If is_dev is set, install from testing deps not just base.
I'd like to do this in AM as well, but I'd like to standardize the requirements files on `base.txt` / `test.txt` / `dev.txt` as done in artefactual/archivematica#490 first, so the ansible role is simpler.
=> SS: Install testing dependencies in dev

tasks/ss-main.yml, vars/main.yml
gettext is used by `manage.py makemessages` and `mange.py compilemessages`
=> Install gettext in dashboard and SS envs

tasks/pipeline-websrv-gunicorn.yml, templates/etc_nginx_sites_dashboard-gunicorn.conf.j2, templates/etc_nginx_sites_dashboard-ssl-gunicorn.conf.j2, templates/etc_nginx_sites_storage-gunicorn.conf.j2, templates/etc_nginx_sites_storage-ssl-gunicorn.conf.j2
The Linux kernel’s sendfile() operation doesn't work well in virtual
environments, truncating long static files. Nginx uses it by default
and this commit disables it if archivematica_src_environment_type
is set to 'development'
=> Disable Nginx sendfile in virtual env, refs #10322

defaults/main.yml, tasks/pipeline-osconf.yml, templates/etc_archivematica_MCPClient_clientConfig.conf.j2, templates/etc_archivematica_MCPServer_serverConfig.conf.j2
I prefer to have my shared directory on a different filesystem, so I just replaced instances of `/var/archivematica/sharedDirectory` with a new ansible variable `archivematica_src_shareddir`.
=> Make shared directory location configurable

tasks/pipeline-osconf.yml, tasks/ss-db.yml, tasks/ss-main.yml
- Check if shared directory exists before attempting to create it (to
avoid errors when it is a symlink)
- Remove unrequired time-consuming commands that change owner/
permissions of objects inside /var/archivematica
=> Fix /var/archivematica/ related tasks

templates/etc_archivematica_archivematicaCommon_dbsettings.j2
added in 1.6.0 archivematica
see https://github.com/artefactual/archivematica/pull/553
allows number of database connections used by MCPClient
or MCPServer to be configured.
=> add max_overflow setting
